instances:
  co_class: 'capacitated_facility_location'
  co_class_kwargs:
    n_customers: 100
    n_facilities: 100


experiment:
  seed: 0
  device: 'cuda:0'
  num_updates: 100000
  buffer_max_size: 10000
  buffer_start_size: 1000


agent:
  name: 'dqn'
  suffix: '_atoms'
  epsilon: 0.1
  # checkpoint: 'outputs/old/capacitated_facility_location/checkpoint_100003.pkl'
  checkpoint: 'outputs/capacitated_facility_location/checkpoint_100073.pkl'

