instances:
  co_class: 'combinatorial_auction'
  co_class_kwargs:
    n_items: 100
    n_bids: 500


experiment:
  seed: 0
  device: 'cuda:0'
  num_updates: 100000
  buffer_max_size: 10000
  buffer_start_size: 1000


agent:
  name: 'dqn'
  epsilon: 0.1
  # checkpoint: 'outputs/combinatorial_auction/checkpoint_100086.pkl'
  # checkpoint: 'outputs/combinatorial_auction_thompson/checkpoint_100026.pkl'
  checkpoint: 'outputs/combinatorial_auction_atoms/checkpoint_100027.pkl'
