instances:
  co_class: 'combinatorial_auction'
  co_class_kwargs:
    n_items: 10
    n_bids: 50


experiment:
  seed: 0
  device: 'cuda:0'
  num_updates: 10000
  buffer_max_size: 1000
  buffer_start_size: 100
  epsilon_decay: 0.999
