instances:
  co_class: 'crabs'
  co_class_kwargs:
    n_time: 12
    n_resources: 20
    n_ships: 35

#instances:
#  co_class: 'tsp'
#  co_class_kwargs:
#    n_nodes: 20
#    planar: False


experiment:
  seed: 0
  device: 'cuda:0'
  num_updates: 1000000
  buffer_max_size: 10000
  buffer_start_size: 1000
  epsilon_decay: 0.99995
