defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

experiment:
  seed: 0
  device: 'cuda:0'
  path_to_bipartite_model: './outputs/cross_entropy_crabs_12_20_35/models/'
  path_to_tripartite_model: './outputs/cross_entropy_crabs_12_20_35/models/'
  path_to_log: './outputs/cross_entropy_crabs_12_20_35/log/'
  test_instances: './outputs/crabs_12_20_35/test/'
  branching: 'explore_then_strong_branch' # 'pure_strong_branch' 'explore_then_strong_branch'
  max_steps: null # None
