instances:
  co_class: 'crabs'
  co_class_kwargs:
    n_time: 12
    n_resources: 20
    n_ships: 35

agent:
  name: 'dqn'
  epsilon: 0.1
  # checkpoint: 'outputs/2022-11-21/13-40-07/checkpoint_548.pkl' -> median = 10.0, std = 175.7791997037387
  checkpoint: 'outputs/2022-11-21/13-40-07/checkpoint_32017.pkl'
  # checkpoint: 'outputs/crabs/checkpoint_120081.pkl' -> median = 12.0, std = 302.6808444460382

output: 'results/dqn_v2.csv'
