defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

instances:
  co_class: 'crabs'
  co_class_kwargs:
    n_time: 12
    n_resources: 20
    n_ships: 35

experiment:
  seed: 123
  device: 'cpu'
  test_instances: './outputs/test/'
  path_to_log: './outputs/log1/'

agent:
  name: 'random'
  epsilon: 1
