defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

instances:
  co_class: 'crabs'
  co_class_kwargs:
    'n_time': 12
    'n_resources': 20
    'n_ships': 35
    'minimize': False

experiment:
  seed: 0
  path_to_save: './outputs/crabs_12_20_35'
  branching: 'explore_then_strong_branch' # 'pure_strong_branch' 'explore_then_strong_branch'
  min_samples: 126000
  max_steps: null # None 3
