defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

instances:
  co_class: 'maximum_independent_set'
  co_class_kwargs:
    'n_nodes': 500

experiment:
  seed: 0
  path_to_save: './outputs/mis_500'
  branching: 'explore_then_strong_branch' # 'pure_strong_branch' 'explore_then_strong_branch'
  min_samples: 126000
  max_steps: null # None 3
