defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

instances:
  co_class: 'combinatorial_auction'
  co_class_kwargs:
    'n_items': 100
    'n_bids': 500

experiment:
  seed: 0
  device: 'cpu'
  path_to_load_imitation_data: './outputs/cauc_100_500/dataset/'
  path_to_save: './outputs/tripartipe_cauc_100_500/models/'
  checkpoint: 84
  path_to_log: './outputs/tripartipe_cauc_100_500/log/'
  test_instances: './outputs/cauc_100_500/test/'
  branching: 'explore_then_strong_branch' # 'pure_strong_branch' 'explore_then_strong_branch'
  max_steps: null # None 3
  num_samples: 100000
  num_epochs: 1000

learner:
  action_mask: True
  observation_format: 'tripartite'
  imitation_target: 'expert_actions' # 'expert_scores' 'expert_score' 'expert_actions' 'expert_bipartite_ranking'
  loss_function: 'cross_entropy' # mean_squared_error cross_entropy jensen_shannon_distance kullback_leibler_divergence
  lr: 0.0001
  epoch_log_frequency: 1
  checkpoint_log_frequency: 1
  name: 'il'

agent:
  name: 'il'
