defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

instances:
  co_class: 'crabs'
  co_class_kwargs:
    'n_months': 12
    'n_places': 20
    'n_ships': 35

experiment:
  seed: 0
  device: 'cuda:0'
  path_to_load_imitation_data: './outputs/crabs_12_20_35/dataset/'
  path_to_save: './outputs/cross_entropy_crabs_12_20_35/models/'
  checkpoint: 80
  path_to_log: './outputs/cross_entropy_crabs_12_20_35/log/'
  test_instances: './outputs/crabs_12_20_35/test/'
  branching: 'explore_then_strong_branch' # 'pure_strong_branch' 'explore_then_strong_branch'
  max_steps: null # None 3
  num_samples: 100000
  num_epochs: 1000

learner:
  observation_format: 'tripartite'
  imitation_target: 'expert_actions' # 'expert_scores' 'expert_score' 'expert_actions' 'expert_bipartite_ranking'
  loss_function: 'cross_entropy' # mean_squared_error cross_entropy jensen_shannon_distance kullback_leibler_divergence
  lr: 0.0001
  epoch_log_frequency: 1
  checkpoint_log_frequency: 1
  name: 'il'

agent:
  name: 'il'
