defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

instances:
  co_class: 'tsp'
  co_class_kwargs:
    'n_nodes': 20

experiment:
  seed: 0
  device: 'cuda:0'
  path_to_load_imitation_data: './outputs/tsp_20/dataset/'
  path_to_save: './outputs/tsp_20/models/'
  checkpoint: 280
  path_to_log: './outputs/tsp_20/log/'
  test_instances: './outputs/tsp_20/test'
  branching: 'explore_then_strong_branch' # 'pure_strong_branch' 'explore_then_strong_branch'
  max_steps: null # None 3
  num_samples: 100000
  num_epochs: 1000
  
learner:
  imitation_target: 'expert_actions' # 'expert_scores' 'expert_score' 'expert_actions' 'expert_bipartite_ranking'
  loss_function: 'cross_entropy' # mean_squared_error cross_entropy jensen_shannon_distance kullback_leibler_divergence
  lr: 0.0001
  epoch_log_frequency: 1
  checkpoint_log_frequency: 1
  name: 'il'

agent:
  name: 'il'
