instances:
  co_class: 'maximum_independent_set'
  co_class_kwargs:
    n_nodes: 500


experiment:
  seed: 0
  device: 'cuda:0'
  num_updates: 100000
  buffer_max_size: 10000
  buffer_start_size: 1000


agent:
  name: 'dqn'
  suffix: '_atoms'
  epsilon: 0.1
  # checkpoint: 'outputs/old/maximum_independent_set/checkpoint_100093.pkl'
  checkpoint: 'outputs/maximum_independent_set/checkpoint_100090.pkl'
