instances:
  co_class: 'set_covering'
  co_class_kwargs:
    n_rows: 165
    n_cols: 230


experiment:
  seed: 0
  device: 'cuda:0'
  num_updates: 1000000
  buffer_max_size: 10000
  buffer_start_size: 1000
  epsilon_decay: 0.99995
