instances:
  co_class: 'set_covering'
  co_class_kwargs:
    n_rows: 500
    n_cols: 100


experiment:
  seed: 0
  device: 'cuda:0'
  num_updates: 100000
  buffer_max_size: 10000
  buffer_start_size: 1000


agent:
  name: 'dqn'
  epsilon: 0.1
  checkpoint: 'unk'
